mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: ar_postcard
  user: root
  password: root
  log_level: dev
system:
  host: 0.0.0.0
  port: :8081
  env: release
redis:
  ip: 43.138.43.19
  port: 6379
  password:
  db: 6
  pool_size: 100
jwt:
  secret: xxx
  expires: 20
  issuer: "xxx"
easyAR:
  cloud_url: https://1c87fb4625bb18cda0ddcb28991831c9.cn1.crs.easyar.com:443
  crs_app_id: e3486b5ea8d8e51b644df6067137d80d
  api_key: 19237b27711bc4d7a4331547ed39ff1a
  api_secret: 3b5c70012d49dd707dbd8f1f5f394ee41f20cdf43889fb969ff9c7f8205f5195
qi_niu:
  access_key: 1HlGSQlD_2sLtyRB9BlOTv7VibTfA48mXQ6zer8D
  secret_key: nz5nqqZjtHFtgCc8eQ6wLZurnEutTrB_7src69jl
  bucket: cinema-admin
  cdn: photo.zjyprofikiller.top
  zone: z2
  size: 5