mysql:
  host: 8.155.34.188
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: ar_postcard
  user: ar_postcard
  password: 38163816aA
  log_level: dev
system:
  host: 0.0.0.0
  port: :8081
  env: release
redis:
  ip: 43.138.43.19
  port: 6379
  password:
  db: 6
  pool_size: 100
jwt:
  secret: xxx
  expires: 20
  issuer: "xxx"
easyAR:
  cloud_url: https://1ff1ae8c39b5d7583f3ab25f8db2a1bc.cn1.crs.easyar.com:443
  crs_app_id: c0214e00fac664ae88430d4c1564a605
  api_key: 7ddd3dc93acf3a5697d740008fedff06
  api_secret: d88e428888d4fa8dab625999d2656349d7bdb73f01d987456a2356cf3c04be2a
qi_niu:
  access_key: 1HlGSQlD_2sLtyRB9BlOTv7VibTfA48mXQ6zer8D
  secret_key: nz5nqqZjtHFtgCc8eQ6wLZurnEutTrB_7src69jl
  bucket: cinema-admin
  cdn: photo.zjyprofikiller.top
  zone: z2
  size: 5